---
dependency:
  name: galaxy

# lint:
#   name: yamllint
#   enabled: true
#   options:
#     config-data:
#       ignore: venv
# provisioner:
#   name: ansible
#   lint:
#     name: ansible-lint
#     options:
#       x: ["403"]
# verifier:
#   name: testinfra
#   lint:
#     name: flake8

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

driver:
  name: docker
platforms:
  - name: redhat-8
    image: registry.access.redhat.com/ubi8/ubi

  - name: redhat-7
    image: registry.access.redhat.com/ubi7/ubi

  - name: centos-8
    image: centos:8

  - name: centos-7
    image: centos:7

  - name: amazonlinux-2
    image: amazonlinux:2

  - name: ubuntu-19.04
    image: ubuntu:19.04

  - name: ubuntu-18.04
    image: ubuntu:18.04

  - name: debian-sid
    image: debian:sid

  - name: debian-buster
    image: debian:buster

  - name: debian-stretch
    image: debian:stretch

scenario:
  name: default
