---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-data:
      ignore: venv

platforms:
  - name: redhat-8
    image: registry.access.redhat.com/ubi8/ubi

  - name: redhat-7
    image: registry.access.redhat.com/ubi7/ubi

  - name: centos-8
    image: centos:8

  - name: centos-7
    image: centos:7

  # - name: centos-6
  #   image: centos:6

  - name: amazonlinux-2
    image: amazonlinux:2

  - name: amazonlinux-1
    image: amazonlinux:1

  - name: ubuntu-18.04
    image: ubuntu:18.04

  - name: debian-sid
    image: debian:sid

  - name: debian-buster
    image: debian:buster

  - name: debian-stretch
    image: debian:stretch

  - name: debian-jessie
    image: debian:jessie


provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["403"]

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
